# Generated by Django 4.0.5 on 2022-06-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombrec', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
            ],
        ),
    ]
