# Generated by Django 4.0.5 on 2022-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=20, null=True, verbose_name='Correo Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=20, null=True, verbose_name='Direccion Cliente'),
        ),
    ]
